server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1012Benq86
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sites:
    - url: https://nopaper.ru/
      name: NoPaper.ru
    - url: https://www.svetlovka.ru/
      name: Svetlovka.ru
#    - url: https://skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru/
#      name: PlayBack.ru
#    - url: https://et-cetera.ru/mobile/
#      name: EtCeteraMobile
#    - url: https://nikoartgallery.com/
#      name: NikoGallery


jsoup-settings:
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
  ignoreHttpErrors: true
  ignoreContentType: true
  referrer: http://www.google.com
