server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1012Benq86
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    charset: utf8mb4
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

#logging:
#  level:
#    jdbc:
#      sqlonly: DEBUG

indexing-settings:
  sites:
#    - url: https://nopaper.ru/
#      name: NoPaper.ru
    - url: https://www.svetlovka.ru/
      name: Svetlovka.ru
    - url: https://shm.ru/
      name: Shm.ru
#    - url: https://www.playback.ru/
#      name: PlayBack.ru
    - url: https://et-cetera.ru/mobile/
      name: EtCeteraMobile.ru
#    - url: https://ipfran.ru/
#      name: Ipfran.ru



jsoup-settings:
  timeout: 120000
  userAgent: Mozilla/5.0 (compatible; YandexAccessibilityBot/3.0; +http://yandex.com/bots)
  ignoreHttpErrors: true
  ignoreContentType: true
  followRedirects: false
  referrer: http://www.google.com
